# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location',
                 models.CharField(choices=[('GZ', 'Guangzhou'), ('KQ', 'Keqiao')], default='GZ', max_length=3)),
                ('stock_in_date', models.DateField()),
                ('stock_out_date', models.DateField(blank=True)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceOfCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_meter', models.FloatField()),
                ('manual_adjust', models.FloatField(blank=True, default=0.0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('order_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.models.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='RollOfCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=20)),
                ('color_name', models.CharField(blank=True, max_length=20)),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('batch_id', models.CharField(blank=True, max_length=20)),
                ('meter', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
        migrations.AddField(
            model_name='clothinstock',
            name='roll_of_cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.RollOfCloth'),
        ),
    ]
