# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('remain_meter', models.FloatField()),
                ('wastage_meter', models.FloatField()),
                ('put_in_time', models.DateField()),
                ('sale_time', models.DateField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='WholeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('batch_id', models.CharField(max_length=20)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('put_in_time', models.DateField()),
                ('sale_time', models.DateField(blank=True)),
                ('meter', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
    ]
