# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=20)),
                ('bank_number', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='名称')),
                ('material', models.CharField(blank=True, max_length=20, verbose_name='材质')),
                ('texture', models.CharField(blank=True, max_length=20, verbose_name='纹理')),
                ('width', models.FloatField(blank=True, default=150, verbose_name='幅宽')),
                ('ref_price', models.FloatField(blank=True, default=0, verbose_name='推荐价格')),
                ('is_per_meter', models.BooleanField(default=True, verbose_name='单位')),
                ('used_for', models.CharField(blank=True, max_length=100, verbose_name='用途')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='详细描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ClothImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ColorMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_color', models.CharField(max_length=10)),
                ('external_color', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='(Different shops which owns the same cloth have different number)', max_length=10)),
                ('price', models.FloatField(blank=True, default=0)),
                ('price_detail', models.CharField(blank=True, max_length=100)),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Ownership')),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('remain_meter', models.FloatField(verbose_name='剩余米数')),
                ('wastage_meter', models.FloatField(verbose_name='损耗米数')),
                ('put_in_time', models.DateTimeField(verbose_name='入库时间')),
                ('sale_time', models.DateTimeField(blank=True, verbose_name='出库时间')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Cloth', verbose_name='布料')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='WholeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('batch_id', models.CharField(max_length=20, verbose_name='缸号')),
                ('is_in_stock', models.BooleanField(default=True)),
                ('put_in_time', models.DateTimeField(verbose_name='入库时间')),
                ('sale_time', models.DateTimeField(blank=True, verbose_name='出库时间')),
                ('meter', models.FloatField(verbose_name='米数')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Cloth', verbose_name='布料')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Shop'),
        ),
        migrations.AddField(
            model_name='colormap',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Ownership'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Shop'),
        ),
    ]
