# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='added_time',
        ),
        migrations.AlterField(
            model_name='ownership',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retail',
            name='put_in_time',
            field=models.DateField(verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='sale_time',
            field=models.DateField(blank=True, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='put_in_time',
            field=models.DateField(verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='sale_time',
            field=models.DateField(blank=True, verbose_name='出库时间'),
        ),
    ]
