# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='is_per_meter',
            field=models.BooleanField(default=True, verbose_name='是否为长度'),
        ),
    ]
