# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 03:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0002_auto_20161025_1127'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=20)),
                ('color_name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20)),
                ('meter', models.FloatField()),
                ('is_in_stock', models.BooleanField(default=True)),
                ('put_in_time', models.DateField()),
                ('sale_time', models.DateField(blank=True)),
                ('stock',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.models.ClothInStock')),
            ],
        ),
        migrations.RemoveField(
            model_name='wholesale',
            name='cloth',
        ),
        migrations.DeleteModel(
            name='WholeSale',
        ),
    ]
