# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0007_auto_20161022_1205'),
        ('stock', '0002_auto_20161012_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clothdetail',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='clothimage',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='clothimageincompany',
            name='cloth_in_company',
        ),
        migrations.RemoveField(
            model_name='clothincompany',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='clothincompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='colormap',
            name='cloth_in_company',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyimage',
            name='company',
        ),
        migrations.AlterField(
            model_name='retail',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth', verbose_name='布料'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth', verbose_name='布料'),
        ),
        migrations.DeleteModel(
            name='BankInfo',
        ),
        migrations.DeleteModel(
            name='Cloth',
        ),
        migrations.DeleteModel(
            name='ClothDetail',
        ),
        migrations.DeleteModel(
            name='ClothImage',
        ),
        migrations.DeleteModel(
            name='ClothImageInCompany',
        ),
        migrations.DeleteModel(
            name='ClothInCompany',
        ),
        migrations.DeleteModel(
            name='ColorMap',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyContact',
        ),
        migrations.DeleteModel(
            name='CompanyImage',
        ),
    ]
