# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('bank_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='名称')),
                ('material', models.CharField(blank=True, max_length=20, verbose_name='材质')),
                ('texture', models.CharField(blank=True, max_length=20, verbose_name='纹理')),
                ('width', models.FloatField(blank=True, default=150, verbose_name='幅宽')),
                ('ref_price', models.FloatField(blank=True, default=0, verbose_name='推荐价格')),
                ('is_per_meter', models.BooleanField(default=True, verbose_name='是否为长度')),
                ('used_for', models.CharField(blank=True, max_length=100, verbose_name='用途')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='详细描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ClothImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ClothImageInCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothInCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True,
                                               help_text='(Different shops which owns the same cloth have different number)',
                                               max_length=10)),
                ('num_of_colors', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0)),
                ('price_detail', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ColorMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_color', models.CharField(max_length=10)),
                ('external_color', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth_in_company',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.ClothInCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=20)),
                ('relationship',
                 models.CharField(choices=[('C', 'Customer'), ('S', 'Supplier'), ('B', 'Both')], default='C',
                                  max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=10)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Company')),
            ],
        ),
        migrations.AddField(
            model_name='clothincompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Company'),
        ),
        migrations.AddField(
            model_name='clothimageincompany',
            name='cloth_in_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.ClothInCompany'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Company'),
        ),
    ]
