# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 03:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOfCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=10)),
                ('color_name', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Cloth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='colormap',
            old_name='external_color',
            new_name='external_color_id',
        ),
        migrations.RenameField(
            model_name='colormap',
            old_name='internal_color',
            new_name='external_color_name',
        ),
        migrations.AddField(
            model_name='colormap',
            name='internal_color_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colormap',
            name='internal_color_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
