# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_date', models.DateField()),
                ('stock_out_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20)),
                ('internal_id', models.CharField(max_length=20)),
                ('color_id', models.CharField(max_length=20)),
                ('color_name', models.CharField(max_length=20)),
                ('price_per_unit', models.FloatField()),
                ('total_units', models.FloatField()),
                ('total_rolls', models.FloatField()),
                ('total_price', models.FloatField()),
                ('is_not_paid', models.BooleanField(default=False)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('is_warehouse', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('order_date', models.DateField()),
                ('deleted_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Cloth')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer',
                                               to='base.BusinessEntity')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier',
                                               to='base.BusinessEntity')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('path', models.FilePathField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PieceOfCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_meter', models.FloatField()),
                ('manual_adjust', models.FloatField(blank=True, default=0.0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('order_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='RollOfCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=20)),
                ('color_name', models.CharField(blank=True, max_length=20)),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('batch_id', models.CharField(blank=True, max_length=20)),
                ('meter', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='roll_of_cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.RollOfCloth'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.Warehouse'),
        ),
    ]
