# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('record', '0002_auto_20161103_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='person_in_charge',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
