# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('record', '0003_auto_20161103_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='width',
            new_name='breadth',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
