# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('record', '0005_auto_20161105_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontactimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='clothimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='clothinshopimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='entityimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='entitypaymentimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='orderimage',
            name='path',
        ),
        migrations.AddField(
            model_name='businesscontactimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothinshopimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entityimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entitypaymentimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
