# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(help_text='(所在单号)', max_length=20, verbose_name='单号')),
                ('order_id', models.CharField(max_length=20, verbose_name='订单编号')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('price_per_unit', models.FloatField(verbose_name='单价')),
                ('total_units', models.FloatField(help_text='(单位为m或kg)', verbose_name='总米数/克重')),
                ('total_bundles', models.FloatField(blank=True, default=0, verbose_name='总匹数')),
                ('total_price', models.FloatField(verbose_name='总价')),
                ('total_paid', models.FloatField(blank=True, default=0, verbose_name='已付金额')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='是否为退单')),
                ('is_warehouse', models.BooleanField(default=False, verbose_name='是否为仓库')),
                ('order_date', models.DateField(verbose_name='下单日期')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cloth',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Cloth', verbose_name='布料')),
                ('customer',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Company', verbose_name='顾客')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.FloatField(verbose_name='米数')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='所属订单')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order')),
            ],
        ),
    ]
