# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0004_auto_20161013_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tmp',
            field=models.DateField(auto_now=True),
        ),
    ]
