# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0005_order_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tmp',
        ),
    ]
