# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0006_remove_order_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Cloth', verbose_name='布料'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.Company', verbose_name='顾客'),
        ),
    ]
