# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='是否付清'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_units',
            field=models.FloatField(help_text='(单位为m或kg)', verbose_name='总米数/重量'),
        ),
    ]
