# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20161010_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='下单日期'),
        ),
    ]
