# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20161002_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='agency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='telephone',
        ),
        migrations.AddField(
            model_name='agency',
            name='contact',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Contact'),
            preserve_default=False,
        ),
    ]
