# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20161012_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='internal_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_not_paid',
            field=models.BooleanField(default=False, verbose_name='欠款'),
        ),
    ]
