# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20161003_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agency',
            name='contact',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='updated_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='created_time',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='updated_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name_main',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name_second',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_number_main',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_number_second',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_main',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_second',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_third',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saleslist',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='has_paid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleslist',
            name='price_per_unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='total_bundles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesList'),
        ),
    ]
