# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20161003_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='own_name',
            new_name='owner_name',
        ),
        migrations.AddField(
            model_name='saleslist',
            name='from_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
