# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20161005_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saleslist',
            name='goods_name',
        ),
        migrations.AddField(
            model_name='goods',
            name='material',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='serial_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='texture',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relations',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Goods'),
        ),
        migrations.AddField(
            model_name='relations',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Shop'),
        ),
    ]
