# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20161005_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('texture', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('width', models.FloatField()),
                ('ref_price', models.FloatField()),
                ('used_for', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Relations',
            new_name='Ownership',
        ),
        migrations.AlterField(
            model_name='ownership',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Cloth'),
        ),
        migrations.AlterField(
            model_name='saleslist',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Cloth'),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
