# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20161005_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='meters',
            new_name='meter',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='from_warehouse',
            new_name='is_warehouse',
        ),
        migrations.AddField(
            model_name='cloth',
            name='image_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='is_per_meter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='saleslist',
            name='total_bundles',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
