# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20161005_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='goods',
            new_name='cloth',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='goods',
            new_name='cloth',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='amount',
            new_name='total_paid',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='has_paid',
            new_name='total_units',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='saleslist',
            name='is_per_meter',
        ),
        migrations.AddField(
            model_name='cloth',
            name='is_per_meter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslist',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Image'),
            preserve_default=False,
        ),
    ]
