# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='price_detail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bank_name_main',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bank_name_second',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bank_number_main',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bank_number_second',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='shop',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_main',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_second',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_third',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
